/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as InsulinRouteImport } from './routes/insulin'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GlucoseRouteImport } from './routes/glucose'
import { Route as ExerciseRouteImport } from './routes/exercise'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MealsNewRouteImport } from './routes/meals.new'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const InsulinRoute = InsulinRouteImport.update({
  id: '/insulin',
  path: '/insulin',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GlucoseRoute = GlucoseRouteImport.update({
  id: '/glucose',
  path: '/glucose',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseRoute = ExerciseRouteImport.update({
  id: '/exercise',
  path: '/exercise',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsNewRoute = MealsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MealsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/exercise': typeof ExerciseRoute
  '/glucose': typeof GlucoseRoute
  '/history': typeof HistoryRoute
  '/insulin': typeof InsulinRoute
  '/meals': typeof MealsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/meals/new': typeof MealsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/exercise': typeof ExerciseRoute
  '/glucose': typeof GlucoseRoute
  '/history': typeof HistoryRoute
  '/insulin': typeof InsulinRoute
  '/meals': typeof MealsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/meals/new': typeof MealsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/exercise': typeof ExerciseRoute
  '/glucose': typeof GlucoseRoute
  '/history': typeof HistoryRoute
  '/insulin': typeof InsulinRoute
  '/meals': typeof MealsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/meals/new': typeof MealsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/exercise'
    | '/glucose'
    | '/history'
    | '/insulin'
    | '/meals'
    | '/settings'
    | '/setup'
    | '/meals/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/exercise'
    | '/glucose'
    | '/history'
    | '/insulin'
    | '/meals'
    | '/settings'
    | '/setup'
    | '/meals/new'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/exercise'
    | '/glucose'
    | '/history'
    | '/insulin'
    | '/meals'
    | '/settings'
    | '/setup'
    | '/meals/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ExerciseRoute: typeof ExerciseRoute
  GlucoseRoute: typeof GlucoseRoute
  HistoryRoute: typeof HistoryRoute
  InsulinRoute: typeof InsulinRoute
  MealsRoute: typeof MealsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insulin': {
      id: '/insulin'
      path: '/insulin'
      fullPath: '/insulin'
      preLoaderRoute: typeof InsulinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glucose': {
      id: '/glucose'
      path: '/glucose'
      fullPath: '/glucose'
      preLoaderRoute: typeof GlucoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise': {
      id: '/exercise'
      path: '/exercise'
      fullPath: '/exercise'
      preLoaderRoute: typeof ExerciseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/new': {
      id: '/meals/new'
      path: '/new'
      fullPath: '/meals/new'
      preLoaderRoute: typeof MealsNewRouteImport
      parentRoute: typeof MealsRoute
    }
  }
}

interface MealsRouteChildren {
  MealsNewRoute: typeof MealsNewRoute
}

const MealsRouteChildren: MealsRouteChildren = {
  MealsNewRoute: MealsNewRoute,
}

const MealsRouteWithChildren = MealsRoute._addFileChildren(MealsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ExerciseRoute: ExerciseRoute,
  GlucoseRoute: GlucoseRoute,
  HistoryRoute: HistoryRoute,
  InsulinRoute: InsulinRoute,
  MealsRoute: MealsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
